# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 企鹅阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '*/20 * * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QQREADHEADERVAL: ${{ secrets.QQREADHEADERVAL }}
        QQREADTIMEHEADERVAL: ${{ secrets.QQREADTIMEHEADERVAL }}
        QQREADTIMEURLVAL: ${{ secrets.QQREADTIMEURLVAL }}
        QQREADURLVAL: ${{ secrets.QQREADURLVAL }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/forGao/MoreCorn.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.QQREADURLVAL
        run: |
          cd ~/Scripts
          npm install
      - name: '运行 【企鹅】'
        if: env.QQREADURLVAL
        run: |
          cd ~/Scripts
          node Task/qqread.js
